variable "vpc_id" {}
variable "privatetgname" {}
variable "public_tg_name" {}
variable "internallbname" {}
variable "loadbalancer_type" {}
variable "internal_lb_sg" {}
variable "private_subnet_lb" {}
variable "private_ec2" {}
variable "public_ec2" {}
variable "external_Lb_name" {}
variable "external_lb_sg" {}
variable "public_subnet_lb" {}